server:
  port: 9527

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.216.129:3306/exercise?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@mariadb
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
